
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vivob
 */
public class KonversiSuhuForm extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhuForm
     */
    public KonversiSuhuForm() {
        initComponents();
        
        /// Menambahkan DocumentListener untuk input suhu
        inputSuhu.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                konversiOtomatis();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                konversiOtomatis();
            }

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                konversiOtomatis();
            }
        });

    }
    
    // Fungsi konversi otomatis
    private void konversiOtomatis() {
        try {
            double suhu = Double.parseDouble(inputSuhu.getText());
            btnKonversiActionPerformed(null); // Panggil logika konversi
        } catch (NumberFormatException e) {
            hasilTextField.setText(""); // Kosongkan hasil jika input tidak valid
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnKonversi = new javax.swing.JButton();
        skalaAwalComboBox = new javax.swing.JComboBox<>();
        inputSuhu = new javax.swing.JTextField();
        hasilTextField = new javax.swing.JTextField();
        celciusRadioButton = new javax.swing.JRadioButton();
        fahrenheitRadioButton = new javax.swing.JRadioButton();
        kelvinRadioButton = new javax.swing.JRadioButton();
        reamurRadioButton = new javax.swing.JRadioButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(198, 198, 249));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel5.setText("Aplikasi Konversi Suhu");
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(214, 234, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Input Suhu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 17);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Suhu Awal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 17);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Suhu Akhir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 17);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Hasil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 17);
        jPanel2.add(jLabel4, gridBagConstraints);

        btnKonversi.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 17);
        jPanel2.add(btnKonversi, gridBagConstraints);

        skalaAwalComboBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        skalaAwalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Suhu-", "Celcius", "Fahrenheit", "Kelvin", "Reamur", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 17);
        jPanel2.add(skalaAwalComboBox, gridBagConstraints);

        inputSuhu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        inputSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputSuhuKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 6, 18);
        jPanel2.add(inputSuhu, gridBagConstraints);

        hasilTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        hasilTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 17);
        jPanel2.add(hasilTextField, gridBagConstraints);

        buttonGroup1.add(celciusRadioButton);
        celciusRadioButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        celciusRadioButton.setText("Celcius");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 17);
        jPanel2.add(celciusRadioButton, gridBagConstraints);

        buttonGroup1.add(fahrenheitRadioButton);
        fahrenheitRadioButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fahrenheitRadioButton.setText("Fahrenheit");
        fahrenheitRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fahrenheitRadioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 17);
        jPanel2.add(fahrenheitRadioButton, gridBagConstraints);

        buttonGroup1.add(kelvinRadioButton);
        kelvinRadioButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        kelvinRadioButton.setText("Kelvin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 6, 18);
        jPanel2.add(kelvinRadioButton, gridBagConstraints);

        buttonGroup1.add(reamurRadioButton);
        reamurRadioButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        reamurRadioButton.setText("Reamur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 6, 18);
        jPanel2.add(reamurRadioButton, gridBagConstraints);

        btnHapus.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 18, 5, 18);
        jPanel2.add(btnHapus, gridBagConstraints);

        btnKeluar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 7, 20);
        jPanel2.add(btnKeluar, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        try {
        // Ambil nilai suhu dari JTextField
        double suhu = Double.parseDouble(inputSuhu.getText());
        double hasil = 0;
        
        // Ambil skala awal dari JComboBox
        String skalaAwal = (String) skalaAwalComboBox.getSelectedItem();
        
        // Cek JRadioButton yang dipilih untuk skala tujuan
        if (fahrenheitRadioButton.isSelected()) {
            // Konversi ke Fahrenheit
            hasil = switch (skalaAwal) {
                case "Celcius" -> (suhu * 9/5) + 32;
                case "Kelvin" -> (suhu - 273.15) * 9/5 + 32;
                case "Reamur" -> (suhu * 9/4) + 32;
                default -> suhu;
            }; // Fahrenheit ke Fahrenheit
        } else if (kelvinRadioButton.isSelected()) {
            // Konversi ke Kelvin
            hasil = switch (skalaAwal) {
                case "Celcius" -> suhu + 273.15;
                case "Fahrenheit" -> (suhu - 32) * 5/9 + 273.15;
                case "Reamur" -> suhu * 5/4 + 273.15;
                default -> suhu;
            }; // Kelvin ke Kelvin
        } else if (reamurRadioButton.isSelected()) {
            // Konversi ke Reamur
            hasil = switch (skalaAwal) {
                case "Celcius" -> suhu * 4/5;
                case "Fahrenheit" -> (suhu - 32) * 4/9;
                case "Kelvin" -> (suhu - 273.15) * 4/5;
                default -> suhu;
            }; // Reamur ke Reamur
        } else if (celciusRadioButton.isSelected()) {
            // Konversi ke celcius
            hasil = switch (skalaAwal) {
                case "Fahrenheit" -> (suhu - 32) * 5/9; 
                case "Kelvin" -> (suhu - 273.15) * 4/5;
                case "Reamur" -> suhu * 5/4 + 273.15;
                default -> suhu;
            }; // Celcius ke Celcius
        
        } else {
            // Tidak ada radio button yang dipilih
            JOptionPane.showMessageDialog(this, "Pilih skala tujuan konversi!");
            return;
        }
        
        // Tampilkan hasil di JTextField hasil
        hasilTextField.setText(String.format("%.2f", hasil));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!");
    }
        
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void fahrenheitRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fahrenheitRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fahrenheitRadioButtonActionPerformed

    private void hasilTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilTextFieldActionPerformed

    private void inputSuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSuhuKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.' && c != '-') {
        evt.consume(); // Membatalkan input selain angka, titik, atau tanda negatif
        }
    }//GEN-LAST:event_inputSuhuKeyTyped

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
         // Kosongkan JTextField input dan hasil
        inputSuhu.setText(""); 
        hasilTextField.setText("");  
    
        // Atur JComboBox ke pilihan awal (index pertama)
        skalaAwalComboBox.setSelectedIndex(0); 
    
        // Hilangkan pilihan pada JRadioButton (menggunakan ButtonGroup)
        buttonGroup1.clearSelection(); 
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKonversi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton celciusRadioButton;
    private javax.swing.JRadioButton fahrenheitRadioButton;
    private javax.swing.JTextField hasilTextField;
    private javax.swing.JTextField inputSuhu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton kelvinRadioButton;
    private javax.swing.JRadioButton reamurRadioButton;
    private javax.swing.JComboBox<String> skalaAwalComboBox;
    // End of variables declaration//GEN-END:variables
}
